apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-cd-deployment-beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-cd-app-beta
  template:
    metadata:
      labels:
        app: sample-cd-app-beta
    spec:
      containers:
      - name: nginx-container
        image: amsy810/echo-nginx:v2.0
